---
# handlers for ivansible.srv_ss

- name: remove stale obfs build dependencies
  apt:
    name: "{{ srv_ss_obfs_build_deps | difference(srv_ss_obfs_build_deps_keep) }}"
    state: absent
    autoremove: true
    autoclean: true
  become: true

- name: remove obfs build directory
  file:
    path: "{{ obfs_build_dir.path }}"
    state: absent
  become: true

- name: restart rsyslog daemon
  systemd:
    name: rsyslog
    state: restarted
  become: true
...
