---
- name: add shadowsocks-libev ppa on xenial
  ansible.builtin.apt_repository:
    repo: ppa:max-c-lv/shadowsocks-libev
    ## see: https://launchpad.net/~max-c-lv/+archive/ubuntu/shadowsocks-libev
    filename: shadowsocks-libev
    mode: 0644
  when: ansible_lsb.codename == 'xenial'
  register: xenial_shadowsocks_ppa_result

- name: update apt cache on xenial for shadowsocks ppa
  ansible.builtin.apt:
    update_cache: true
  when: xenial_shadowsocks_ppa_result is changed

- name: install shadowsocks-libev package
  ansible.builtin.apt:
    name: shadowsocks-libev
  register: ss_install_result


- name: send shadowsocks syslog to dedicated log
  ansible.builtin.copy:
    src: rsyslog.conf
    dest: /etc/rsyslog.d/33-shadowsocks.conf
    force: true
    mode: 0644
  notify: restart syslog service

- name: rotate shadowsocks log
  ansible.builtin.template:
    src: logrotate.conf
    dest: /etc/logrotate.d/shadowsocks
    mode: 0644
...
