---
- name: use import to become root globally
  ansible.builtin.import_tasks: root.yml
  become: true
  when: srv_ss_enable |bool
  tags:
    - srv_ss_all
    - srv_shadowsocks_all

- name: run delayed handlers now
  ansible.builtin.meta: flush_handlers
  tags:
    - srv_ss_all
    - srv_shadowsocks_all
...
