---
- name: create simple-obfs build directory
  ansible.builtin.tempfile:
    state: directory
    prefix: simple-obfs.
  register: obfs_build_dir
  notify: remove obfs build directory

- name: checkout simple-obfs sources
  ansible.builtin.git:
    repo: https://github.com/shadowsocks/simple-obfs.git
    dest: "{{ obfs_build_dir.path }}"
    version: "{{ srv_ss_obfs_version }}"
    update: false

- name: install simple-obfs build dependencies
  ansible.builtin.apt:
    name: "{{ srv_ss_obfs_build_deps + srv_ss_obfs_build_deps_keep }}"
    state: present
    install_recommends: false
  notify: remove stale obfs build dependencies

- name: build and install simple-obfs
  # noqa 303 306 - cannot use git module here; no pipes here
  ansible.builtin.shell: >
    git submodule update --init --recursive &&
    ./autogen.sh &&
    ./configure &&
    make &&
    make install
    {% if (srv_ss_obfs_binary |dirname) != '/usr/local/bin' %}
    && mv /usr/local/bin/obfs-server "{{ srv_ss_obfs_binary }}"
    && mv /usr/local/bin/obfs-local "{{ srv_ss_obfs_binary |dirname }}"
    {% endif %}
  args:
    chdir: "{{ obfs_build_dir.path }}"
    creates: "{{ srv_ss_obfs_binary }}"

- name: remove temporary build stuff now
  ansible.builtin.meta: flush_handlers
...
