---
- name: install nginx
  ansible.builtin.import_tasks: install.yml
  tags: lin_nginx_install

- name: setup nginx directories
  ansible.builtin.import_tasks: dirs.yml
  tags: lin_nginx_dirs

- name: create base nginx configration files
  ansible.builtin.import_tasks: config.yml
  tags: lin_nginx_config

- name: configure nginx security and tls
  ansible.builtin.import_tasks: tls.yml
  tags: lin_nginx_tls

- name: configure nginx sites
  ansible.builtin.import_tasks: site.yml
  tags: lin_nginx_site

- name: activate nginx service
  ansible.builtin.import_tasks: run.yml
  tags: lin_nginx_run

- name: fine-tune nginx logs
  ansible.builtin.import_tasks: logs.yml
  tags: lin_nginx_logs
...
