---
- name: create cache directories before activating nginx
  ansible.builtin.include_tasks: flush-handlers.yml

- name: start nginx while taking care of apache
  block:
    - name: enable nginx service (will be rescued if it fails)
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: true
        daemon_reload: true

  rescue:
    ## Note: apache2 may come pre-installed on some cheap hostings
    - name: disable apache2 service (it may block http port)
      ansible.builtin.systemd:
        name: apache2
        state: stopped
        enabled: false
      register: stop_apache2_result
      ignore_errors: true
      no_log: "{{ hide_secrets |bool }}"

    - name: pause a little to let http port go free in background
      ansible.builtin.pause:
        seconds: 3
      when: stop_apache2_result is changed

    - name: enable nginx service once again
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: true
        masked: false
        daemon_reload: true

- name: open nginx ports in ufw
  community.general.ufw:
    rule: allow
    ## force string conversion to prevent module warning
    port: "{{ item |string }}"
    proto: tcp
  loop: "{{ web_ports }}"
  no_log: "{{ hide_secrets |bool }}"
  when: lin_firewall == 'ufw'

- name: open nginx ports in ferm
  ivansible.base.ferm_port:
    port: "{{ web_ports }}"
    proto: tcp
    comment: nginx
  tags: skip_ansible_lint
  when: lin_firewall == 'ferm'

- name: open internal nginx ports in ferm
  ivansible.base.ferm_port:
    port:
      - "{{ nginx_http_port_internal |d('',true) }}"
      - "{{ nginx_ssl_port_internal |d('',true) }}"
    proto: tcp
    zone: internal
    comment: nginx internal
  tags: skip_ansible_lint
  when: lin_firewall == 'ferm'

- name: enable nginx transparent proxying in ferm
  ivansible.base.ferm_rule:
    name: nginx-transparent
    prio: 42
    hook: custom
    rule: "{{ lookup('template', 'transparent.ferm') }}"
  tags: skip_ansible_lint
  when:
    - nginx_transparent |bool
    - lin_firewall == 'ferm'
...
