---
- name: create directory for default nginx site
  ansible.builtin.file:
    path: "{{ nginx_def_site_dir }}"
    state: directory
    mode: 0755

- name: upload www files for default nginx site
  ansible.builtin.copy:
    src: "www/{{ item }}"
    dest: "{{ nginx_def_site_dir }}/{{ item }}"
    force: true
    mode: 0644
  loop:
    - favicon.ico
    - index.html
    - robots.txt
  tags: lin_nginx_site_files

- name: remove obsolete default nginx sites
  ansible.builtin.file:
    path: "{{ nginx_site_dir }}/{{ item }}"
    state: absent
  loop:
    - default
    - 0.default.conf
  notify: restart nginx service

- name: create configuration for default nginx site
  ansible.builtin.template:
    src: default-site.conf
    dest: "{{ nginx_site_dir }}/default.conf"
    mode: 0644
  notify:
    - restart nginx service
    ## detect changed binding of https port
    - restart sslh service

- name: find all configured nginx sites
  ansible.builtin.find:
    paths: "{{ nginx_site_dir }}"
    recurse: false
    patterns: ['*.conf', '*.inc']
  register: all_nginx_sites

- name: update ipv4 bind interface on existing nginx sites
  ansible.builtin.replace:
    path: "{{ item.path }}"
    regexp: 'listen\s+(127\.0\.0\.1:|0\.0\.0\.0:|)(443|{{ nginx_ssl_port }}|{{ nginx_ssl_port_local }})\s+ssl(\s+http2)?'
    replace: "{{ nginx_conf_listen_ssl_ipv4 }}"
  loop: "{{ all_nginx_sites.files }}"
  loop_control:
    label: "{{ item.path |basename }}"
  notify:
    - restart nginx service
    ## detect changed binding of https port
    - restart sslh service

- name: update ipv6 bind interface on existing nginx sites
  ansible.builtin.replace:
    path: "{{ item.path }}"
    regexp: 'listen\s+\[::1?\]:(443|{{ nginx_ssl_port }}|{{ nginx_ssl_port_local }})\s+ssl(\s+http2)?'
    replace: "{{ nginx_conf_listen_ssl_ipv6 }}"
  loop: "{{ all_nginx_sites.files }}"
  loop_control:
    label: "{{ item.path |basename }}"
  notify:
    - restart nginx service
    ## detect changed binding of https port
    - restart sslh service
...
