---
- name: create group for proxy processes
  group:
    name: proxy
    gid: 13

- name: create directory for main service snap-in
  file:
    path: /etc/systemd/system/shadowsocks-libev.service.d
    state: directory

- name: link directory for additional services snap-in
  file:
    state: link
    dest: /etc/systemd/system/shadowsocks-libev-server@.service.d
    src: shadowsocks-libev.service.d

- name: set effective group of shadowsocks service to "proxy"
  copy:
    dest: /etc/systemd/system/shadowsocks-libev.service.d/group.conf
    content: |
      [Service]
      # set group to "proxy" to activate sslh iptables fix
      Group=proxy
  register: ss_proxyfix_result

- name: disable use of ambient capabilities on old kernels
  copy:
    dest: /etc/systemd/system/shadowsocks-libev.service.d/caps.conf
    content: |
      {% if ansible_kernel is version('4.3', '>') %}
      # local kernel {{ essential_kernel_release }} supports ambient capabilities
      {% else %}
      [Service]
      # local kernel {{ essential_kernel_release }} does not support ambient capabilities
      # we can still run as user nobody because low ports are not used
      AmbientCapabilities=
      {% endif %}
  vars:
    ## keep only major/minor componenets in kernel release number because
    ## micro components frequently change after kernel upgrades
    ## and cause extra change reports
    essential_kernel_release: "{{ ansible_kernel |regex_replace('^([0-9]+[.][0-9]+).+$','\\1+') }}"
  register: ss_kernelfix_result
...
