---
- name: add shadowsocks-libev ppa on xenial
  apt_repository:
    repo: ppa:max-c-lv/shadowsocks-libev
    # see: https://launchpad.net/~max-c-lv/+archive/ubuntu/shadowsocks-libev
    filename: shadowsocks-libev
  when: ansible_lsb.codename == 'xenial'
  register: xenial_shadowsocks_ppa_result

- name: update apt cache on xenial for shadowsocks ppa
  apt:
    update_cache: true
  when: xenial_shadowsocks_ppa_result is changed

- name: install shadowsocks-libev package
  apt:
    name: shadowsocks-libev
  register: ss_install_result

- name: send shadowsocks syslog to dedicated log
  copy:
    src: rsyslog.conf
    dest: /etc/rsyslog.d/33-shadowsocks.conf
    force: false
  notify: restart rsyslog daemon

- name: rotate shadowsocks log
  copy:
    src: logrotate.conf
    dest: /etc/logrotate.d/shadowsocks
    force: false
...
