---
- name: create configuration for backend [{{ backend.name }}]
  template:
    src: nginx-backend.conf
    dest: /etc/nginx/bastion.d/shadowsocks-{{ backend.name }}.conf
  notify: reload nginx service

- name: configure site mirroring
  template:
    src: nginx-mirrors.conf
    dest: /etc/nginx/sites-enabled/mirrors.conf
  notify: reload nginx service
...
