---
- name: create simple-obfs build directory
  tempfile:
    state: directory
    prefix: simple-obfs.
  register: obfs_build_dir
  notify: remove obfs build directory

- name: checkout simple-obfs sources
  git:
    repo: https://github.com/shadowsocks/simple-obfs.git
    dest: "{{ obfs_build_dir.path }}"
    version: master
    update: false

- name: install simple-obfs build dependencies
  apt:
    name: "{{ srv_ss_obfs_build_deps + srv_ss_obfs_build_deps_keep }}"
    state: present
    install_recommends: false
  notify: remove stale obfs build dependencies

- name: build and install simple-obfs
  # noqa 303 - cannot use git module here
  shell: >
    git submodule update --init --recursive &&
    ./autogen.sh &&
    ./configure &&
    make &&
    make install
  args:
    chdir: "{{ obfs_build_dir.path }}"
    creates: "{{ srv_ss_obfs_binary }}"

- name: remove temporary build stuff now
  meta: flush_handlers
...
