---
- name: use import to become root globally
  ansible.builtin.import_tasks: root.yml
  become: true
  tags: lin_uwsgi_all

- name: restart uwsgi now
  ansible.builtin.meta: flush_handlers
  tags: lin_uwsgi_all
...
