---
namespace: ivansible
name: nginx
version: 1.0.0

description: Ansible collection for Nginx derivatives

authors:
  - Ivan Andreev <ivandeex@gmail.com>

tags:
  - linux
  - nginx
  - uwsgi
  - sslh
  - cdn
  - proxy
  - chisel
  - doh
  - shadowsocks
  - v2ray
  - squid
  - communigate

# https://python-semanticversion.readthedocs.io/en/latest/#requirement-specification
# namespace.name: version_range
dependencies: {}

repository: https://github.com/ivansible/nginx
documentation: https://github.com/ivansible/nginx
homepage: https://github.com/ivansible/nginx
issues: https://github.com/ivansible/nginx/issues

readme: README.md
license: MIT

build_ignore:
  - '*.pyc'
  - '*.tar'
...
