---
dependencies:
  - ivansible.base.linux  # for lin_firewall, ferm_port module and more
  - ivansible.base.nginx  # for nfinx snippet directories
  # - ivansible.nginx.cdn  # for cloudflare task (implicit dependency)

galaxy_info:
  role_name: srv_squid
  author: "Ivan Andreev"
  description: "install and configure squid with ssl"
  company: "IvanSible"
  license: MIT
  min_ansible_version: 2.5

  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic

  galaxy_tags:
    - linux
    - server
    - proxy
    - squid

  github_branch: master
...
