---
- name: prepare
  hosts: all
  roles:
    - ivansible.linux.core
    - ivansible.nginx.nginx
  tasks:
    - name: stop exim from taking port 25 on github runners
      systemd:
        name: exim4
        state: stopped
        masked: true
      become: true
      failed_when: false
      when: ansible_connection == 'local'
...
