---
# defaults for ivansible.lin_nginx

nginx_base_domain: "{{ web_domain }}"
nginx_main_site: ""

nginx_xframe_uri: "https://{{ nginx_main_site }}"  # URI or 'same' or 'none'
nginx_cache_enable: true
nginx_behind_vpn: true
nginx_upload_progress: false
nginx_cloudflare_ips: []
nginx_cloudfront_ips: []

nginx_snimux_port: "{{ use_sslh |bool |ternary(3443, nginx_ssl_port) }}"
nginx_nossl_upstream_port: 0

## listen on public interfaces only if local and public ssl ports overlap
## listen everywhere when transparency is on because it cannot handle overlap anyway
nginx_ssl_listen_addr: "{{ '*' if nginx_ssl_port |int != nginx_ssl_port_local |int
                           else _nginx_ssl_listen_pub }}"
_nginx_ssl_listen_pub: "{{ [ansible_default_ipv4.address |d(''),
                            ansible_default_ipv6.address |d(''),
                            ansible_all_ipv4_addresses |d([]) |ansible.utils.ipaddr('public')]
                           |flatten |select |sort |unique }}"

## transparent proxying (enabled in ivansible.base.nginx)
## note: the mark must literally match hexadecimal output of `ip rule ls`
nginx_mark_value: '0x2'
nginx_lookup_table: '102'

nginx_own_default_server: true

# stable or mainline repository?
nginx_prefer_stable: false

nginx_use_resolver: true
# use fallback resolver by default
# nginx_resolver: 8.8.8.8

nginx_max_logs: ~

nginx_user: "{{ web_user }}"
nginx_group: "{{ web_group }}"
nginx_workers: auto   # 2

nginx_base_dir: /etc/nginx
nginx_cache_dir: /run/nginx
nginx_log_dir: /var/log/nginx
nginx_pid_file: /run/nginx.pid
...
