---
## CommunigatePro debian package forgets to create symbolic links
## for mail and sendmail in /usr/bin. Let's fix it.

## === /usr/bin/mail ===

- name: create cgpro link for /usr/bin/mail
  ansible.builtin.file:
    state: link
    src: /opt/CommuniGate/mail
    dest: /usr/bin/mail.cgpro

- name: check that /usr/bin/mail exists
  ansible.builtin.stat:
    path: /usr/bin/mail
    get_checksum: false
  register: usr_bin_mail_check

- name: backup stock /usr/bin/mail
  when: usr_bin_mail_check.stat.exists
  ## use readlink + hardlink to preserve node type
  ansible.builtin.shell:
    # noqa 302
    cmd: ln $(realpath /usr/bin/mail) /usr/bin/mail.stock
    warn: false
    creates: /usr/bin/mail.stock

- name: setup cgpro alternative for /usr/bin/mail
  ## the `alternatives` module does not support slaves
  ## so we use a low-level command
  ansible.builtin.command: >-
    update-alternatives
      --install /usr/bin/mailx mailx /opt/CommuniGate/mail 50
      --slave   /usr/bin/mail  mail  /opt/CommuniGate/mail
  register: mail_alternatives_result
  changed_when:
    mail_alternatives_result.stdout.find('forcing reinstallation') != -1

## === /usr/sbin/sendmail ===

- name: create cgpro link for sbin/sendmail
  ansible.builtin.file:
    state: link
    src: /opt/CommuniGate/sendmail
    dest: /usr/sbin/sendmail.cgpro

- name: check that /usr/sbin/sendmail exists and is a regular file
  ansible.builtin.stat:
    path: /usr/sbin/sendmail
    get_checksum: false
  register: usr_sbin_sendmail_check

- name: backup stock /usr/sbin/sendmail (if it exists and not a symbolic link)
  ansible.builtin.command:
    cmd: mv /usr/sbin/sendmail /usr/sbin/sendmail.stock
    creates: /usr/sbin/sendmail.stock
  when:
    - usr_sbin_sendmail_check.stat.exists
    - usr_sbin_sendmail_check.stat.isreg
  register: stock_sendmail_backup

- name: create vanilla alternative for /usr/sbin/sendmail
  when: stock_sendmail_backup is changed
  community.general.alternatives:
    name: sendmail
    link: /usr/sbin/sendmail
    path: /usr/sbin/sendmail.stock

- name: setup cgpro alternative for /usr/sbin/sendmail
  community.general.alternatives:
    name: sendmail
    link: /usr/sbin/sendmail
    path: /opt/CommuniGate/sendmail
...
