---
- name: installation overview
  ansible.builtin.debug:
    msg:
      - "domains: {{ cgpro_domains | join(' ') }}"
      - "certificate: {{ cgpro_ssl_cert }}"
      - "reset: {{ cgpro_reset }}"
      - "restore: {{ cgpro_restore }}"
  tags:
    - cgpro_all
    - srv_cgpro_all

- name: perform cgpro tasks as root
  ansible.builtin.import_tasks: root.yml
  become: true
  when: lin_apt_arch == 'amd64'  ## cgpro is unavailable on arm
  tags:
    - cgpro_all
    - srv_cgpro_all

- name: flush handlers
  ansible.builtin.meta: flush_handlers
...
