---
- name: check that role lin_nginx is deployed
  ansible.builtin.stat:
    path: "{{ nginx_def_site_dir }}/favicon.ico"
    get_checksum: false
  register: check_nginx_site_dir

- name: deploy role lin_nginx
  ## Condition for this step will be rarely true.
  ## Prefer include (vs import) to avoid lots of skip messages.
  ansible.builtin.include_role:
    name: ivansible.nginx.nginx
    apply:
      tags: [cgpro_nginx, cgpro_all]
  when: not check_nginx_site_dir.stat.exists

- name: deploy custom cgpro favicon
  ansible.builtin.get_url:
    url: "{{ cgpro_favicon_url }}"
    dest: "{{ nginx_def_site_dir }}/favicon-cgpro.ico"
    mode: 0644
  register: _cgpro_favicon_result
  until: _cgpro_favicon_result is successful

- name: configure cgpro webmail for nginx
  ansible.builtin.template:
    src: cgpro-mail.nginx.conf
    dest: "{{ nginx_site_dir }}/cgpro-mail.conf"
    lstrip_blocks: true
    mode: 0644
  notify: reload nginx service

- name: configure cgpro admin site for nginx
  ansible.builtin.template:
    src: cgpro-admin.nginx.conf
    dest: "{{ nginx_site_dir }}/cgpro-admin.conf"
    lstrip_blocks: true
    mode: 0644
  notify: reload nginx service
...
