---
- name: install cgpro
  ansible.builtin.import_tasks: install.yml
  tags: cgpro_install


- name: (re)create cgpro base directory
  block:
    - name: completely purge cgpro base directory (reset all settings)
      ansible.builtin.file:
        path: "{{ cgpro_dir }}"
        state: absent
      when: cgpro_reset |bool

    - name: check that cgpro base directory exists (appear changed if not)
      ## note: this check must go before the first service run
      ##       because the service will create the folder under test
      ansible.builtin.stat:
        path: "{{ cgpro_dir }}"
      register: cgpro_dir_check
      changed_when: not cgpro_dir_check.stat.exists
      notify: restart cgpro service

    - name: create or recreate cgpro base directory and set permissions
      ansible.builtin.file:
        path: "{{ cgpro_dir }}"
        state: directory
        owner: root
        group: mail
        mode: 02770  # drwxrws---
  tags: cgpro_dir


## CommunigatePro debian package forgets to create symbolic links
- name: fix symbolic links for mail and sendmail in /usr/bin
  ansible.builtin.import_tasks: alternatives.yml
  when: cgpro_dpkg_check |d({}) is changed
        or cgpro_dir_check |d({}) is changed
        or cgpro_reset |bool
  tags: cgpro_alternatives

- name: setup and enable cgpro service
  ansible.builtin.import_tasks: service.yml
  tags: cgpro_service


- name: first time setup of a new cgpro deployment
  ansible.builtin.import_tasks: first-run.yml
  when: cgpro_dir_check |d({}) is changed
  tags:
    - cgpro_firstrun
    - cgpro_configure


- name: restore cgpro from backup
  ansible.builtin.import_tasks: restore.yml
  when: cgpro_restore |bool
  tags: cgpro_restore

- name: create a script for making more cgpro backups
  ## script usage: sudo -E cgpro-make-backup.sh [aes]
  ansible.builtin.template:
    src: cgpro-make-backup.sh
    dest: /usr/local/bin/
    owner: root
    group: root
    mode: 0750
  tags: cgpro_restore


- name: configure cgpro settings (http method)
  ansible.builtin.import_tasks: configure.yml
  tags: cgpro_configure

- name: configure some cgpro settings (obsolete pwd method)
  ## This step is normally skipped.
  ## Prefer include (vs import) to avoid lots of skip messages.
  ansible.builtin.include_tasks: configure-pwd.yml
  when: false
  tags: cgpro_configure


- name: configure cgpro ports
  ansible.builtin.import_tasks: configure-ports.yml
  tags:
    - cgpro_configure
    - cgpro_ports

- name: open cgpro ports in ufw
  community.general.ufw:
    rule: allow
    port: "{{ item |string }}"
    proto: tcp
  no_log: "{{ hide_secrets |bool }}"
  loop: "{{ cgpro_open_ports }}"
  when: lin_firewall == 'ufw'
  tags:
    - cgpro_firewall

- name: open cgpro ports in ferm
  ivansible.base.ferm_port:
    port: "{{ cgpro_open_ports }}"
    proto: tcp
    comment: cgpro
  when: lin_firewall == 'ferm'
  tags:
    - skip_ansible_lint
    - cgpro_firewall


- name: set server ssl certificate in cgpro
  ansible.builtin.import_tasks: ssl.yml
  tags: cgpro_ssl

- name: configure cgpro interface skin
  ansible.builtin.include_tasks: skin.yml
  when:
    - skin.name is defined
    - skin.url is defined
  loop: "{{ cgpro_skins }}"
  loop_control:
    loop_var: skin
    label: "{{ skin.name | default('null') }}"
  tags: cgpro_skin

- name: integrate cgpro with nginx
  ansible.builtin.import_tasks: nginx.yml
  tags: cgpro_nginx
...
