---
- name: get list of cgpro trusted certificate authorities
  ansible.builtin.uri:
    url: &url_cacerts "{{ cgpro_curl_url }}/Domains/TrustedCommon.html"
    user: postmaster
    password: "{{ cgpro_postmaster_password }}"
    method: GET
    return_content: true
    use_proxy: false
  environment: {no_proxy: '*'}
  register: cacerts_page

- name: add new cgpro trusted certificate authorities (skip in check mode)
  ansible.builtin.uri:
    url: *url_cacerts
    headers:
      Referer: *url_cacerts
    user: postmaster
    password: "{{ cgpro_postmaster_password }}"
    method: POST
    body_format: form-urlencoded
    body:
      FormCharset: utf-8
      Create: Set Certificate
      Certificate: "{{ lookup('file', item.file) }}"
    follow_redirects: all
    return_content: false
    use_proxy: false
  environment: {no_proxy: '*'}
  when:
    ## the uri task above is skipped in check mode and produces no connent
    - not ansible_check_mode
    - cacerts_page.content.find(needle) == -1
  vars:
    has_serial: "{{ item.serial |default('') != '' }}"  # noqa 602
    needle: "{{ '<tt>%s</tt>' % item.serial if has_serial else '<td>%s</td>' % item.name }}"
  loop: "{{ cgpro_trusted_cacerts }}"
  loop_control:
    label: "{{ item.name }}"


- name: verify that cgpro ssl certificate and key exist on remote host
  ansible.builtin.file:
    path: "{{ item }}"
    state: file
  loop:
    - "{{ cgpro_ssl_cert }}"
    - "{{ cgpro_ssl_key }}"


- name: create directory for cgpro certificate script
  ansible.builtin.file:
    path: "{{ cgpro_cert_update_script |dirname }}"
    state: directory
    mode: 0755

- name: create a script for uploading certificate to cgpro
  ansible.builtin.template:
    src: cgpro-update-certificate.sh
    dest: "{{ cgpro_cert_update_script }}"
    owner: root
    group: root
    mode: 0750
  register: upload_script_result

- name: directory for letsencrypt post-renewal hooks
  ansible.builtin.file:
    path: "{{ certbot_post_dir }}"
    state: directory
    mode: 0755
  when: cgpro_ssl_cert is search('/letsencrypt/')

- name: link a letsencrypt post-renewal hook for cgpro
  ansible.builtin.file:
    state: link
    src: "{{ cgpro_cert_update_script }}"
    dest: "{{ certbot_post_dir }}/cgpro"
  when: cgpro_ssl_cert is search('/letsencrypt/')

- name: upload certificate and private key to cgpro
  ansible.builtin.command:
    cmd: "{{ cgpro_cert_update_script }}"
  when: upload_script_result is changed
        or cgpro_dir_check | d({}) is changed
...
