---
# defaults for ivansible.srv_ss

srv_ss_configs: []

srv_ss_defaults:
  name: default
  password: secret
  method: aes-128-cfb
  bindip: 0.0.0.0
  port: 9443
  local_port: 1080
  fast: true
  reuse: true
  # mode: tcp_and_udp
  mode: ""
  timeout: 600
  direct: true
  plugin: none
  web_path: /

srv_ss_v2ray_version: latest
srv_ss_v2ray_allow_reinstall: false
srv_ss_v2ray_binary: /usr/local/sbin/v2ray-plugin

# obfs plugin is obsolete, disabled by default
srv_ss_obfs_enable: false
srv_ss_obfs_version: v0.0.5
srv_ss_obfs_binary: /usr/local/sbin/obfs-server

srv_ss_obfs_build_deps:
  - autoconf
  - automake
  - libtool
  - asciidoc
  - xmlto
  - libssl-dev
  - libpcre3-dev
  - libc-ares-dev
  - libev-dev

srv_ss_obfs_build_deps_keep:
  - build-essential
...
