---
- name: add deadsnakes ppa on xenial
  ansible.builtin.apt_repository:
    repo: ppa:deadsnakes/ppa
    filename: deadsnakes
    mode: 0644
  when: ansible_lsb.codename == 'xenial'
  tags: srv_dyndns_python38

- name: install python3.8
  ansible.builtin.apt:
    name:
      - python3.8
      - python3.8-dev
      - python3.8-venv
  tags: srv_dyndns_python38

- name: install pip requirements for dyndns
  ansible.builtin.pip:
    name:
      - cloudflare
      - pysocks
      - paramiko
      - cryptography < 3.4
    virtualenv: /usr/local/dyndns
    virtualenv_command: python3.8 -m venv

- name: install dyndns python executable
  ansible.builtin.copy:
    src: dyndns.py
    dest: /usr/local/sbin/dyndns
    force: true
    mode: 0755
  notify: restart dyndns service
  tags:
    - srv_dyndns_script
    - srv_dyndns_service
...
