---
- name: become root and install dynamic dns service
  ansible.builtin.import_tasks: root.yml
  become: true
  tags: srv_dyndns_all
  when: srv_dyndns_enable |bool

- name: run postponed handlers now
  ansible.builtin.meta: flush_handlers
...
