---
# defaults for ivansible.lin_nginx

nginx_base_domain: "{{ web_domain }}"
nginx_main_site: ""

nginx_xframe_uri: "https://{{ nginx_main_site }}"  # URI or 'same' or 'none'
nginx_cache_enable: true
nginx_behind_vpn: true
nginx_upload_progress: false
nginx_cloudflare_ips: []
nginx_cloudfront_ips: []

nginx_sni_mux_port: 3443
nginx_sni_servers: []
# - comment: server1
#   hostname: host1.example.com
#   port: 9999

# stable or mainline repository?
nginx_prefer_stable: false

nginx_use_resolver: true
# use fallback resolver by default
# nginx_resolver: 8.8.8.8

nginx_max_logs: ~

nginx_user: "{{ web_user }}"
nginx_group: "{{ web_group }}"
nginx_workers: auto   # 2

nginx_base_dir: /etc/nginx
nginx_cache_dir: /run/nginx
nginx_log_dir: /var/log/nginx
nginx_pid_file: /run/nginx.pid
...
