---
- name: disable sslh service (please ignore possible failure, it's expected)
  ansible.builtin.systemd:
    name: sslh
    state: stopped
    enabled: false
  failed_when: false
  no_log: "{{ hide_secrets |bool }}"

- name: remove sslh snippet from ferm
  ivansible.base.ferm_rule:
    name: sslh
    hook: custom
    state: absent
    # reload: false
  tags:
    - lin_sslh_firewall
    - skip_ansible_lint
  when: lin_firewall == 'ferm'

- name: remove sslh package
  ansible.builtin.apt:
    name: sslh
    state: absent
    purge: true

- name: remove sslh configuration files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/default/sslh
    - /etc/sslh.cfg
    - /etc/systemd/system/sslh.service
    - /etc/systemd/system/sslh.service.d
    - /usr/local/sbin/sslh-helper-ufw.sh
    - /usr/local/sbin/sslh-helper-iptables.sh  # obsolete
...
