---
- name: install chisel binary
  ansible.builtin.import_tasks: install.yml
  tags: srv_chisel_install

- name: create group for proxy processes
  ansible.builtin.group:
    name: proxy
    gid: 13

- name: configure chisel service
  ansible.builtin.template:
    src: chisel-server.defaults
    dest: /etc/default/chisel-server
    owner: root
    group: proxy
    mode: 0640
  notify: restart chisel service

- name: setup chisel service
  ansible.builtin.template:
    src: chisel-server.service
    dest: /etc/systemd/system/chisel-server.service
    mode: 0644
  notify: restart chisel service

- name: directory for nginx backend configs
  ansible.builtin.file:
    path: /etc/nginx/mixin.d
    state: directory
    mode: 0755

- name: configure nginx redirector for chisel
  ansible.builtin.template:
    src: chisel-server.nginx.conf
    dest: /etc/nginx/mixin.d/chisel.conf
    mode: 0644
  notify: reload nginx service

- name: activate chisel service
  ansible.builtin.systemd:
    name: chisel-server
    state: started
    enabled: true
    daemon_reload: true

- name: open (or block) chisel port in ufw
  community.general.ufw:
    port: "{{ srv_chisel_port |string }}"
    proto: tcp
    rule: "{{ srv_chisel_direct |bool |ternary('allow','deny') }}"
  no_log: "{{ hide_secrets |bool }}"
  when: lin_firewall == 'ufw'

- name: open (or block) chisel port in ferm
  ivansible.base.ferm_port:
    port: "{{ srv_chisel_port }}"
    proto: tcp
    zone: "{{ srv_chisel_direct |bool |ternary('external','internal') }}"
    solo_zone: true
    comment: chisel
  tags: skip_ansible_lint
  when: lin_firewall == 'ferm'
...
