---
- name: setup dns records in cloudflare for cdn
  ansible.builtin.import_tasks: cloudflare.yml
  vars:
    records: "{{ srv_cdn_cloudflare |default([]) }}"
  when:
    - srv_cdn_cloudflare is defined
  tags:
    - srv_cdn_cloudflare
    - srv_cdn_all

- name: setup cloudfront distributions for cdn
  ansible.builtin.import_tasks: cloudfront.yml
  when:
    - srv_cdn_cloudfront |d([],true)
    - not (srv_cdn_cloudfront_disable |bool)
  tags:
    - srv_cdn_cloudfront
    - srv_cdn_all

- name: create directory for nginx mixin configurations
  ansible.builtin.file:
    path: "{{ nginx_root_dir }}/mixin.d"
    state: directory
    mode: 0755
  become: true
  tags:
    - srv_cdn_nginx
    - srv_cdn_all

- name: configure cdn mappings in nginx (will skip in check mode)
  ansible.builtin.template:
    src: cdn.conf
    dest: "{{ nginx_site_dir }}/cdn.conf"
    mode: 0644
  become: true
  notify: reload nginx service
  ## this task depends on "cloudfront distributions" failing in check mode
  when: not ansible_check_mode
  tags:
    - srv_cdn_nginx
    - srv_cdn_all

- name: configure simple cdn site in nginx
  ansible.builtin.template:
    src: cdn.inc
    dest: "{{ nginx_site_dir }}/cdn.inc"
    mode: 0644
  become: true
  notify: reload nginx service
  tags:
    - srv_cdn_nginx_site
    - srv_cdn_nginx
    - srv_cdn_all

- name: apply new nginx settings
  ansible.builtin.meta: flush_handlers
  tags:
    - srv_cdn_all
...
