---
## handlers for ivansible.srv_squid

- name: restart squid service
  ansible.builtin.systemd:
    name: "{{ squid_pkg }}"
    state: restarted
  become: true

- name: hold squid upgrades
  ansible.builtin.command: apt-mark hold "{{ squid_pkg }}"
  become: true
...
