---
- name: backup vanilla nginx configuration (optional, so ok to fail)
  command:
    argv:
      - cp
      - -a
      - "{{ nginx_base_dir }}/nginx.conf"
      - "{{ nginx_base_dir }}/nginx.conf.orig"
    creates: "{{ nginx_base_dir }}/nginx.conf.orig"
  ignore_errors: true

- name: select nginx fallback resolver on xenial
  set_fact:
    # assume installed dnsmasq or bind9
    nginx_fallback_resolver: 127.0.0.1
  when:
    - ansible_lsb.codename in ['xenial']
    - nginx_fallback_resolver is not defined

- name: select nginx fallback resolver on bionic+
  set_fact:
    # fallback to systemd-resolved on bionic+
    nginx_fallback_resolver: 127.0.0.53
  when:
    - ansible_lsb.codename not in ['xenial']
    - nginx_fallback_resolver is not defined

- name: create main nginx configuration file
  template:
    src: nginx.conf
    dest: "{{ nginx_base_dir }}/nginx.conf"
    mode: 0644
  notify: restart nginx service

- name: uwsgi parameters for nginx behind balancer
  template:
    src: uwsgi_params
    dest: "{{ nginx_base_dir }}/uwsgi_params"
    mode: 0644
  notify: restart nginx service

- name: comment for extra mime types
  lineinfile:
    path: "{{ nginx_base_dir }}/mime.types"
    regexp: "# \\w+ mime"
    line: "    # custom mime types"
    insertbefore: "^}"

- name: let nginx know some extra mime types
  lineinfile:
    path: "{{ nginx_base_dir }}/mime.types"
    regexp: "{{ item.split().0 }}\\s"
    line: "    {{ item }};"
    insertbefore: "^}"
  loop:
    - "application/x-ns-proxy-autoconfig     pac"
    - "application/x-pkcs12                  p12"
    - "application/x-pkcs7-crl               crl"
    - "application/x-x509-ca-cert            der pem crt cer"
  loop_control:
    label: "{{ item.split().0 }}"
  notify: restart nginx service

- name: configure nginx proxies
  template:
    src: proxies.conf
    dest: "{{ nginx_conf_dir }}/proxies.conf"
    mode: 0644
  notify: restart nginx service

- name: configure nginx stream multiplexor
  template:
    src: tlsmux.conf
    dest: "{{ nginx_stream_dir }}/tlsmux.conf"
    mode: 0644
  notify: restart nginx service
...
