---
- name: limit number of nginx logs
  lineinfile:
    path: /etc/logrotate.d/nginx
    regexp: '^(\s*rotate)\s+\d+'
    line: '\1 {{ nginx_max_logs }}'
    backrefs: true
    backup: true
  when: nginx_max_logs |default(0) |int

- name: create nginx cache directories
  file:
    path: "{{ nginx_cache_dir }}"
    state: directory
    owner: "{{ web_user }}"
    group: root
    mode: 0750

- name: activate nginx cache directories in systemd
  when: nginx_cache_enable | bool
  copy:
    content: "d    {{ nginx_cache_dir }}    0750    {{ web_user }}    root    -       -"
    dest: /etc/tmpfiles.d/nginx.conf
  notify: update system temp files

- name: directory for included nginx configuration files
  file:
    path: "{{ nginx_conf_dir }}"
    state: directory

- name: directory for included nginx site configurations
  file:
    path: "{{ nginx_site_dir }}"
    state: directory

- name: directory for nginx password files
  file:
    path: "{{ nginx_base_dir }}/users"
    state: directory
    owner: root
    group: "{{ web_group }}"
    mode: 0750
...
