---
- name: install nginx signing key
  apt_key:
    url: http://nginx.org/keys/nginx_signing.key

- name: add nginx apt repository
  apt_repository:
    repo: "deb [arch=amd64] http://nginx.org/packages/{{ repo_path }}/ {{ codename }} nginx"
    filename: nginx
    update_cache: true
  vars:
    repo_path: "{{ nginx_prefer_stable |bool |ternary('ubuntu', 'mainline/ubuntu') }}"
    codename: "{{ ansible_lsb.codename }}"
  register: nginx_repo_result
  until: nginx_repo_result is successful

- name: install nginx and ssl packages
  apt:
    name:
      - nginx
      - ssl-cert  # for snakeoil certificate
    state: present
...
