---
- name: limit number of nginx logs
  lineinfile:
    path: /etc/logrotate.d/nginx
    regexp: '^(\s*rotate)\s+\d+'
    line: '\1 {{ nginx_max_logs }}'
    backrefs: true
    backup: true
  when: nginx_max_logs |default(0) |int

- name: enable/disable compression of nginx logs
  replace:
    path: /etc/logrotate.d/nginx
    regexp: "{{ lookbehind }}(compress|delaycompress)"
    replace: "{{ commentout }}\\1"
  vars:
    lookbehind: "{{ lin_compress_logs |bool |ternary('(?:#\\s*)','(?<!#)') }}"
    commentout: "{{ lin_compress_logs |bool |ternary('','#') }}"
  when: lin_compress_logs is not none
...
