---
- name: install nginx
  import_tasks: install.yml
  tags: lin_nginx_install

- name: setup nginx directories
  import_tasks: dirs.yml
  tags: lin_nginx_dirs

- name: create base nginx configration files
  import_tasks: config.yml
  tags: lin_nginx_config

- name: configure nginx security and tls
  import_tasks: tls.yml
  tags: lin_nginx_tls

- name: configure nginx sites
  import_tasks: site.yml
  tags: lin_nginx_site

- name: activate nginx service
  import_tasks: run.yml
  tags: lin_nginx_run
...
