---
- name: create cache directories before activating nginx
  include_tasks: flush-handlers.yml

- name: enable nginx service
  systemd:
    name: nginx
    state: started
    enabled: yes
    daemon_reload: yes

- name: open nginx ports
  ufw:
    rule: allow
    # force string conversion to prevent module warning
    port: "{{ item |string }}"
    proto: tcp
  loop: "{{ web_ports }}"
...
