---
dependencies:
  - ivansible.base.linux     # for common settings and modules
  - ivansible.base.nginx     # for ssl certificate and nginx config snippets
  - ivansible.base.backup    # for unarchive_encrypted.yml
  - ivansible.base.cert      # for common certbot settings
  ## the following roles are imported directly from tasks:
  # - ivansible.nginx.nginx

galaxy_info:
  role_name: cgpro
  author: "Ivan Andreev"
  description: "deploy CommuniGate Pro server on a linux host"
  company: "IvanSible"
  license: MIT
  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic

  galaxy_tags:
    - linux
    - server
    - mail
    - web
    - cgpro
    - communigate
    - communigatepro

  github_branch: master
...
