---
- name: install sslh package
  apt:
    name: sslh
    state: present

- name: add dual ipv4/ipv6 localhost in /etc/hosts as sslh target
  blockinfile:
    path: /etc/hosts
    block: |
      127.0.0.1 localhost4or6
      ::1       localhost4or6
    marker: "# {mark} dual-stack target for sslh"
  notify: restart sslh service

- name: create sslh config file
  template:
    src: sslh.cfg
    dest: /etc/sslh.cfg
    owner: root
    group: sslh
    mode: 0640
  notify: restart sslh service

- name: override sslh service settings
  template:
    src: sslh.service
    dest: /etc/systemd/system/sslh.service
    owner: root
    group: root
    mode: 0644
  notify: restart sslh service

- name: create group for proxy processes
  group:
    name: proxy
    gid: 13
  when: sslh_proxy_fix |bool

- name: configure helper parameters for sslh
  blockinfile:
    path: /etc/default/sslh
    block: |
      PROXY_PORTS={{ sslh_proxy_ports }}
      LOOKUP_TABLE={{ sslh_lookup_table }}
      MARK_VALUE={{ sslh_mark_value }}
      MARK_MASK={{ sslh_mark_mask }}
      # TRANSPARENT_SETCAP must be one of: enable, disable, ignore
      TRANSPARENT_SETCAP={{ sslh_transparent_setcap }}
    marker: "# {mark} sslh helper parameters"
  notify: restart sslh service

- name: install sslh helpers
  copy:
    src: "{{ item }}"
    dest: /usr/local/sbin/sslh-helper-{{ item }}
    owner: root
    group: root
    mode: 0754
  loop:
    - proxy-fix.sh
    - transparent.sh
  notify: restart sslh service

- name: open https port for sslh
  ufw:
    rule: allow
    port: "443"
    proto: tcp
  no_log: true

- name: enable and start sslh service (will be rescued if it fails)
  systemd:
    name: sslh
    state: started
    enabled: yes
  register: sslh_service_start_result

- name: determine whether nginx service runs (and possibly blocks ssl port)
  service_facts:
  # note: condition "ActiveState == 'failed'" is not enough
  when: sslh_service_start_result.status.ActiveState != 'active'

- name: let sslh service start when nginx blocks ssl port due to stale settings
  block:
    - name: prevent pending sslh restart before nginx gets reconfigured
      meta: flush_handlers

    - name: stop nginx to unblock bound ssl port (will restart after reconfiguration)
      systemd:
        name: nginx
        state: stopped
      register: nginx_service_stop_result
      # make few attempts until nginx really stops
      until: nginx_service_stop_result.status.ActiveState != 'active'
      notify: restart nginx service
      # sometimes change is not detected but we know for sure nginx was running
      changed_when: true

    - name: pause a little to let ssl port go free in background
      pause:
        seconds: 3

    - name: start sslh service once again after stopping nginx
      systemd:
        name: sslh
        # perform restart instead of start to override stuck service state
        state: started
        enabled: yes

  when: sslh_service_start_result.status.ActiveState != 'active'
        and ansible_facts.services.nginx is defined
        and ansible_facts.services.nginx.state == 'running'
...
