---
## handlers for ivansible.srv_ss
## handler 'restart syslog service' is imported from ivansible.lin_base

- name: remove stale obfs build dependencies
  ansible.builtin.apt:
    name: "{{ srv_ss_obfs_build_deps | difference(srv_ss_obfs_build_deps_keep) }}"
    state: absent
    autoremove: true
    autoclean: true
  become: true

- name: remove obfs build directory
  ansible.builtin.file:
    path: "{{ obfs_build_dir.path }}"
    state: absent
  become: true
...
