---
- name: become root and install rust-doh
  ansible.builtin.import_tasks: root.yml
  become: true
  tags: srv_doh_all

- name: remove rust-doh compilation files now
  ansible.builtin.meta: flush_handlers
  tags: srv_doh_all
...
