---
- name: check that rust-doh binary already exists
  ansible.builtin.stat:
    path: "{{ srv_doh_binary }}"
    get_checksum: false
  register: stat_doh_binary
  tags: srv_doh_install

- name: install rust-doh binary from zip or deb, or compile
  ansible.builtin.include_tasks: install.yml
  args:
    apply:
      tags:
        - srv_doh_install
        - srv_doh_all
      become: true
  when: srv_doh_upgrade |bool
        or not stat_doh_binary.stat.exists
  tags: srv_doh_install

- name: create group for proxy processes
  ansible.builtin.group:
    name: proxy
    gid: 13

- name: configure rust-doh service
  ansible.builtin.template:
    src: rust-doh.defaults
    dest: /etc/default/rust-doh
    owner: root
    group: proxy
    mode: 0640
  notify: restart rust-doh service

- name: setup rust-doh service unit
  ansible.builtin.template:
    src: rust-doh.service
    dest: /etc/systemd/system/rust-doh.service
    mode: 0644
  notify: restart rust-doh service

- name: directory for nginx backend configs
  ansible.builtin.file:
    path: /etc/nginx/mixin.d
    state: directory
    mode: 0755

- name: configure nginx redirector for rust-doh
  ansible.builtin.template:
    src: rust-doh.nginx.conf
    dest: /etc/nginx/mixin.d/rust-doh.conf
    mode: 0644
  notify: reload nginx service

- name: activate rust-doh service
  ansible.builtin.systemd:
    name: rust-doh
    state: started
    enabled: true
    daemon_reload: true
...
