---
# defaults for ivansible.lin_sslh

#use_sslh: <inherited from ivansible.nxinx_base>

sslh_tls_port: 443
sslh_ssh_port: 22
sslh_ssh_fork: false
sslh_ssh_timeout: 16
sslh_openvpn_port: 0
sslh_socks5_port: 0
sslh_anyprot_port: 443

sslh_sni_servers: []
## list of SNI forwards:
#  - {comment: COMMENT1, hostname: SNI_HOSTNAME_1, port: LOCAL_PORT_1}
#  - {comment: COMMENT2, hostname: SNI_HOSTNAME_2, port: LOCAL_PORT_2}
## ...

sslh_verbose: false
sslh_handle_http: true
sslh_nonroot: "{{ ansible_kernel is version('4.3', '>') }}"

# Note: transparency fails on OpenVZ
sslh_transparent: "{{ lin_firewall in ['ufw', 'ferm'] }}"
sslh_lookup_table: 100
# Note: the mark must literally match the output of "ip rule ls" (hexadecimal)
sslh_mark_value: '0x1'

sslh_listen_addresses:
  - "{{ ansible_default_ipv4.address }}"
  - "{{ ansible_default_ipv6.address |default('') }}"

sslh_bionic_deb: http://mirrors.kernel.org/ubuntu/pool/universe/s/sslh/sslh_1.18-1_amd64.deb
sslh_focal_deb: http://mirrors.kernel.org/ubuntu/pool/universe/s/sslh/sslh_1.20-1_amd64.deb
...
