---
# defaults for ivansible.lin_sslh

#use_sslh: <inherited from ivansible.nxinx_base>

sslh_ssh_port: 22
sslh_ssh_fork: false
sslh_ssh_timeout: 16
sslh_openvpn_port: 0
sslh_socks5_port: 0
sslh_anyprot_port: 443

sslh_verbose: false
sslh_handle_http: true
sslh_nonroot: "{{ ansible_kernel is version('4.3', '>') }}"

# Note: transparency fails on OpenVZ
sslh_transparent: "{{ lin_firewall in ['ufw', 'ferm'] }}"
sslh_lookup_table: 100
sslh_mark_value: 0x01

sslh_listen_addresses:
  - "{{ ansible_default_ipv4.address }}"
  - "{{ ansible_default_ipv6.address |default('') }}"
...
