---
- name: create directory for v2ray-core files
  ansible.builtin.file:
    path: /usr/local/v2ray
    state: directory
    mode: 0755
  tags: srv_v2ray_install

- name: detect latest v2ray-core release
  ivansible.base.github_release:
    repository: v2fly/v2ray-core
    release: "{{ srv_v2ray_version }}"
    template: "{download_url}/{{ tarball_name }}"
    strip_v: true
    version_script: "{{ srv_v2ray_binary }} -version"
    script_regex: '[0-9]+[.][0-9._-]+'
    reinstall: "{{ srv_v2ray_upgrade |bool }}"
  register: latest_v2ray_core_release
  notify: restart v2ray service
  vars:
    tarball_amd64: v2ray-linux-64.zip
    tarball_arm64: v2ray-linux-arm64-v8a.zip
    tarball_name: "{{ tarball_arm64 if ansible_architecture == 'aarch64' else tarball_amd64 }}"
  tags:
    - skip_ansible_lint
    - srv_v2ray_install

- name: download and unpack v2ray-core archive
  ansible.builtin.unarchive:
    remote_src: true
    src: "{{ latest_v2ray_core_release.url }}"
    dest: "{{ srv_v2ray_binary |dirname }}"
  when: latest_v2ray_core_release is changed
  notify: restart v2ray service
  tags: srv_v2ray_install


- name: directory for v2ray config files
  ansible.builtin.file:
    path: /etc/v2ray
    state: directory
    mode: 0755
  tags: srv_v2ray_config

- name: update v2ray configuration
  ansible.builtin.template:
    src: v2ray.config.json
    dest: /etc/v2ray/config.json
    owner: root
    group: proxy
    mode: 0640
  notify: restart v2ray service
  tags: srv_v2ray_config


- name: directory for nginx backend configs (including v2ray)
  ansible.builtin.file:
    path: /etc/nginx/mixin.d
    state: directory
    mode: 0755
  tags: srv_v2ray_nginx

- name: configure nginx redirector for v2ray
  ansible.builtin.template:
    src: v2ray.nginx.conf
    dest: /etc/nginx/mixin.d/v2ray.conf
    mode: 0644
  notify:
    - restart v2ray service
    - reload nginx service
  tags: srv_v2ray_nginx


- name: create group for proxy processes (including v2ray)
  ansible.builtin.group:
    name: proxy
    gid: 13
  tags: srv_v2ray_service

- name: setup v2ray systemd service
  ansible.builtin.template:
    src: v2ray.service
    dest: /etc/systemd/system/v2ray-server.service
    mode: 0644
  notify: restart v2ray service
  register: v2ray_systemd_service_result
  tags: srv_v2ray_service

- name: activate v2ray systemd service
  ansible.builtin.systemd:
    name: v2ray-server
    state: started
    enabled: true
    daemon_reload: "{{ v2ray_systemd_service_result is changed }}"
  tags: srv_v2ray_service


- name: open/block v2ray port in ufw
  community.general.ufw:
    port: "{{ srv_v2ray_port |string }}"
    proto: tcp
    rule: "{{ srv_v2ray_direct |bool |ternary('allow','deny') }}"
  no_log: "{{ hide_secrets |bool }}"
  when: lin_firewall == 'ufw'
  tags: srv_v2ray_firewall

- name: open/block v2ray port in ferm
  ivansible.base.ferm_port:
    port: "{{ srv_v2ray_port }}"
    proto: tcp
    zone: "{{ srv_v2ray_direct |bool |ternary('external','internal') }}"
    solo_zone: true
    comment: v2ray
  tags:
    - skip_ansible_lint
    - srv_v2ray_firewall
  when: lin_firewall == 'ferm'
...
