---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: xenial
    image: ivandeex/molecule:16.04
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups:
      - molecule
  - name: bionic
    image: ivandeex/molecule:18.04
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups:
      - molecule
provisioner:
  name: ansible
  inventory:
    group_vars:
      molecule:
        ansible_user: ansible
        linbase_system_locale: en_US.UTF-8
        allow_sysctl: false
        linbase_time_sync: false
        lin_use_firewall: ${IVATEST_FIREWALL:-true}
        lin_use_ssh: ${IVATEST_SSH_SERVER:-true}
        lin_systemd_tmpfiles: ${IVATEST_SYSTEMD_TMPFILES:-true}
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
    options:
      max-line-length: 120
lint:
  name: yamllint
  options:
    config-file: .yamllint.yml
scenario:
  name: default
  converge_sequence:
    - converge
  test_sequence:
    - lint
    - dependency
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
...
