---
- name: verify
  hosts: all
  tasks:
    - name: verify cgpro on amd64
      block:
        - name: gather facts about cgpro service
          service_facts:
        - name: cgpro service must be running
          assert:
            that: ansible_facts.services['cgpro.service'].state == 'running'
        - name: cgpro service must be enabled
          assert:
            that: ansible_facts.services['cgpro.service'].status == 'enabled'

        - name: assert that mail site works
          command: >
            curl -ksL https://{{ host }}
              --resolve {{ host }}:443:{{ addr }}
              --resolve {{ host }}:80:{{ addr }}
          vars:
            host: mail.example.com
            addr: 127.0.0.1
          args:
            warn: false
          changed_when: false
          register: html_mail
        - name: mail site must respond on ports 80/443
          assert:
            that: html_mail.stdout is search('Welcome to CommuniGate Pro,')

        - name: assert that admin site works
          command: >
            curl -ksL https://{{ host }}
              --resolve {{ host }}:443:{{ addr }}
              --resolve {{ host }}:80:{{ addr }}
          vars:
            host: cgpro.example.com
            addr: 127.0.0.1
          args:
            warn: false
          changed_when: false
          register: html_admin
        - name: mail site response must contain cgpro banner
          assert:
            that: html_admin.stdout is search('Welcome to CommuniGate Pro Server Administration.')

        - name: assert that smtp port answers
          # noqa command-instead-of-shell
          shell: nc -v -w1 localhost 25
          args:
            stdin: ""
            warn: false
          changed_when: false
          register: reply_smtp
        - name: smtp port sesponse must contain cgpro banner
          assert:
            that: reply_smtp.stdout is search('ESMTP CommuniGate Pro')

      ## end of block
      when: ansible_architecture == 'x86_64'  # unavailable on arm
...
