---
dependencies:
  # inherit parameter use_sslh from nginx_base
  - ivansible.nginx_base

galaxy_info:
  role_name: lin_sslh
  author: "Ivan Andreev"
  description: "setup sslh on linux"
  company: "IvanSible"
  license: MIT
  min_ansible_version: 2.5

  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic

  galaxy_tags:
    - linux
    - ansible
    - sslh

  github_branch: master
...
