---
- name: become root and install squid
  ansible.builtin.import_tasks: root.yml
  become: true
  vars:
    lecert_name: "{{ squid_letsencrypt_cert |d('',true) }}"
    lecert_dir: "/etc/letsencrypt/live/{{ lecert_name }}"
    lecert_bundle: "{{ squid_etc_dir }}/ssl-letsencrypt.pem"
    self_signed: "{{ lecert_name in ['', 'example.com'] }}"
    ss_cert: "{{ squid_etc_dir }}/ssl-selfsigned"
  when:
    - squid_enable |bool
    ## llxdev ppa lacks arm64 package
    - not (squid_from_ppa |bool and lin_apt_arch == 'arm64')
  tags: srv_squid_all

- name: apply squid changes now
  ansible.builtin.meta: flush_handlers
  tags: srv_squid_all
...
