---
all:
  children:
    molecule:
      children:
        docker_molecule:
          vars:
            ansible_user: ansible
            lin_systemd_tmpfiles: true
        local_molecule:
          vars:
            lin_systemd_tmpfiles: false
      vars:
        is_permitted: false
        allow_sysctl: false
        lin_use_ssh: false
        lin_firewall: none
        lin_core_time_sync: false
        lin_core_system_locale: en_US.UTF-8

        srv_dyndns_cloudflare_email: dummy
        srv_dyndns_run_as_root: true
...
